# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gogtfobins < Formula
  desc ""
  homepage ""
  version "1.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juliendoutre/gogtfobins/releases/download/v1.11.0/gogtfobins_Darwin_x86_64.tar.gz"
      sha256 "1bcb6eb8891b2fc9bad74ca30b5165b46f12bb35402537fde4baa30478cebf62"

      def install
        bin.install "gogtfobins"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juliendoutre/gogtfobins/releases/download/v1.11.0/gogtfobins_Darwin_arm64.tar.gz"
      sha256 "380951ead35d7cf1c98fd6b3e9699b5a539582765cff055901204639b1f2e4b7"

      def install
        bin.install "gogtfobins"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/gogtfobins/releases/download/v1.11.0/gogtfobins_Linux_x86_64.tar.gz"
        sha256 "d669d4bdde67d01d510e7e91871fad80b1c638f76656c1f62f884bf5f300d614"

        def install
          bin.install "gogtfobins"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/gogtfobins/releases/download/v1.11.0/gogtfobins_Linux_arm64.tar.gz"
        sha256 "dbae6d0466a971dc8af2a69a55696918cbf4810f4f53720e8a610c78bca1703b"

        def install
          bin.install "gogtfobins"
        end
      end
    end
  end
end
