# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gogtfobins < Formula
  desc ""
  homepage ""
  version "1.15.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juliendoutre/gogtfobins/releases/download/v1.15.0/gogtfobins_Darwin_x86_64.tar.gz"
      sha256 "f0558f40419304987c088aebfe3cfcc5616675f4d04611d617c548d498031fb1"

      def install
        bin.install "gogtfobins"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juliendoutre/gogtfobins/releases/download/v1.15.0/gogtfobins_Darwin_arm64.tar.gz"
      sha256 "2fba9f0d8a33f956b83309f3f360efc7951af49de8f0fe63c1813e20edabc1d4"

      def install
        bin.install "gogtfobins"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/gogtfobins/releases/download/v1.15.0/gogtfobins_Linux_x86_64.tar.gz"
        sha256 "d3a30edeee65c4ddd2a6d22cc65b9920dceaab33ed9b4f9b6048f18f6f824fb2"

        def install
          bin.install "gogtfobins"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/gogtfobins/releases/download/v1.15.0/gogtfobins_Linux_arm64.tar.gz"
        sha256 "932873740bd99356d301d2dbdbb3f42fe12bb58103a8a43b51be2ec0b78db12f"

        def install
          bin.install "gogtfobins"
        end
      end
    end
  end
end
