# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gogtfobins < Formula
  desc ""
  homepage ""
  version "1.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juliendoutre/gogtfobins/releases/download/v1.9.0/gogtfobins_Darwin_x86_64.tar.gz"
      sha256 "7269633342acb0d3f31aa9899f6dc252e953215ecd981b9741ea2d0fdec1f232"

      def install
        bin.install "gogtfobins"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juliendoutre/gogtfobins/releases/download/v1.9.0/gogtfobins_Darwin_arm64.tar.gz"
      sha256 "1d39fb8d0b2fa330307005843a8c65dad5f2b75dd2f5a9324fba4acbbb213901"

      def install
        bin.install "gogtfobins"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/gogtfobins/releases/download/v1.9.0/gogtfobins_Linux_x86_64.tar.gz"
        sha256 "3f84f68085ea1517686b8e1927c754ba710576303e2c1c4f912e30e5f98d9dcd"

        def install
          bin.install "gogtfobins"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/gogtfobins/releases/download/v1.9.0/gogtfobins_Linux_arm64.tar.gz"
        sha256 "bacecd4551a1e60f3ec34eb5286128431f059882fcb331db630588b7b6d67b82"

        def install
          bin.install "gogtfobins"
        end
      end
    end
  end
end
